version: '3.9'
services:
  welcome:
    build:
      context: .
      dockerfile: ./apps/welcome/Dockerfile
      args:
        - appname=welcome
    image: openhmis-welcome
    
    ports:
      - 8700:80
  patient-phr:
    build:
      context: .
      dockerfile: ./apps/patient/phr/Dockerfile
      args:
        - appname=phr
    image: openhmis-patient-phr    
    ports:
      - 8701:80