version: '3.9'
services:
  welcome:
    build:
      context: .
      dockerfile: ./apps/welcome/Dockerfile
      args:
        - appname=welcome
    image: railtelhrit.jfrog.io/openhmis-docker/welcome:latest
    ports:
      - 8700:80
  patient-phr:
    build:
      context: .
      dockerfile: ./apps/patient/phr/Dockerfile
      args:
        - appname=phr
    image: railtelhrit.jfrog.io/openhmis-docker/patient-phr:latest
    ports:
      - 8701:80