POST https://rcmapi.instaalerts.zone/services/rcm/sendMessage
Content-Type: application/json
Authorization: Bearer mMgc81jsBwUv1DO5svEcXA==
Authentication: Bearer mMgc81jsBwUv1DO5svEcXA==

{
    "message": {
        "channel": "WABA",
        "content": {
            "preview_url": false,
            "shorten_url": false,
            "type": "MEDIA_TEMPLATE",
            "mediaTemplate": {
                "templateId": "au_doc",
                "media": {
                    "type": "document",
                    "url": "https://www.antennahouse.com/XSLsample/pdf/sample-link_1.pdf"
                },
                "bodyParameterValues": {"0":"*ABC*", "1":"*Account Statement*"}
            }
        },
        "recipient": {
            "to": "9960969563",
            "recipient_type": "individual"
        },
        "sender": {
            "from": "917760686668"
        },
        "preferences": {
            "webHookDNId": "1001"
        }
    },
    "metaData": {
        "version": "v1.0.9"
    }
}