apiVersion: apps/v1
kind: Deployment
metadata:
  name: phr
  namespace: openhmis
spec:
  selector:
    matchLabels:
      app: phr
  template:
    metadata:
      labels:
        app: phr
    spec:
      imagePullSecrets:
        - name: jfrogcred
      containers:
      - name: phr
        image: railtelhrit.jfrog.io/openhmis-docker/patient-phr:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phr-service
  namespace: openhmis
spec:
  selector:
    app: phr
  ports:
  - port: 80
    targetPort: 80
