apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome
spec:
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
      - name: welcome
        image: railtelhrit.jfrog.io/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
