apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome
  namespace: openhmis
spec:
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      imagePullSecrets:
        - name: jfrogcred
      containers:      
      - name: welcome        
        image: railtelhrit.jfrog.io/openhmis-docker/welcome:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: welcome-service
  namespace: openhmis
spec:
  selector:
    app: welcome
  ports:
  - port: 80
    targetPort: 80

